# Ignored dirs (.git, .venv), extensions

DEFAULT_IGNORED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
    "node_modules",
    ".tox",
    "site-packages",
}

DEFAULT_IGNORED_EXTS = {
    ".scip",
    ".pyc",
    ".pyo",
    ".pyd",
    ".so",
    ".dylib",
    ".dll",
    ".log",
}

SYMBOL_KIND_MAP = {
    "function_definition": "function",
    "function_declaration": "function",
    "arrow_function": "function",
    "class_definition": "class",
    "class_declaration": "class",
    "variable_declarator": "function",  # because your query only matches arrow functions
}

# BUILTIN_FUNCTIONS = {
#     "print",
#     "len",
#     "range",
#     "str",
#     "int",
#     "float",
#     "list",
#     "dict",
#     "set",
#     "tuple",
#     "enumerate",
#     "zip",
#     "map",
#     "filter",
#     "isinstance",
#     "issubclass",
#     "getattr",
#     "setattr",
#     "hasattr",
#     "delattr",
#     "type",
#     "dir",
#     "id",
#     "open",
#     "super",
#     "Exception",
#     "ValueError",
#     "TypeError",
# }

# Python built-ins to filter out if you only want meaningful application calls
PYTHON_BUILTINS = {
    "print",
    "len",
    "range",
    "enumerate",
    "isinstance",
    "issubclass",
    "int",
    "str",
    "float",
    "bool",
    "list",
    "dict",
    "set",
    "tuple",
    "open",
    "super",
    "getattr",
    "setattr",
    "hasattr",
    "iter",
    "next",
    "min",
    "max",
    "sum",
    "any",
    "all",
    "zip",
    "repr",
    "id",
    "type",
}